name: 'Continuous Integration and Deployment'

on:
  pull_request:
    types: [opened, synchronize]
  workflow_run:
    workflows: [ "Deploy to pre-demo & demo" ]
    types: [completed]
  workflow_dispatch:

jobs:
  slow-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate long-running tests
        run: |
          echo "🕒 Starting fake tests..."
          sleep 10
          echo "✅ Fake tests completed after 30 seconds!"
