name: 'Continuous Integration and Deployment'

on:
  push:
    branches:
      - dev
      - pre-demo
      - demo
  pull_request:
    types: [opened, synchronize]
  workflow_call:

jobs:
  slow-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate long-running tests
        run: |
          echo "🕒 Starting fake tests..."
          sleep 10
          echo "✅ Fake tests completed after 30 seconds!"
